---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-General-Hierarchical
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  Clone::PP: 1.02
  Config::General: 2.49
  Cwd: 0
  Scalar::Util: 1.18
  Test::Differences: 0.47
version: 0.07
